name       : python-asn1-modules
version    : 0.2.2
release    : 4
source     :
    - https://files.pythonhosted.org/packages/source/p/pyasn1-modules/pyasn1-modules-0.2.2.tar.gz : a0cf3e1842e7c60fde97cb22d275eb6f9524f5c5250489e292529de841417547
license    : BSD-2-Clause
component  : programming.python
summary    : A collection of ASN.1-based protocols modules
description: |
    A collection of ASN.1 modules expressed in form of pyasn1 classes. Includes protocols PDUs definition (SNMP, LDAP etc.) and various data structures (X.509, PKCS etc.).
builddeps  :
    - python-asn1
rundeps    :
    - python-asn1
    - python-openssl
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
check      : |
    %python_test
    %python3_test
