name       : python-asn1-modules
version    : 0.2.3
release    : 5
source     :
    - https://pypi.io/packages/source/p/pyasn1-modules/pyasn1-modules-0.2.3.tar.gz : d14fcb29dabecba3d7b360bf72327c26c385248a5d603cf6be5f566ce999b261
license    : BSD-2-Clause
component  : programming.python
summary    : A collection of ASN.1-based protocols modules
description: |
    A collection of ASN.1 modules expressed in form of pyasn1 classes. Includes protocols PDUs definition (SNMP, LDAP etc.) and various data structures (X.509, PKCS etc.).
builddeps  :
    - python-asn1
rundeps    :
    - python-asn1
    - python-openssl
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
check      : |
    %python_test
    %python3_test
