name       : python-asn1-modules
version    : 0.2.7
release    : 7
source     :
    - https://files.pythonhosted.org/packages/75/93/c51104ea6a74252957c341ccd110b65efecc18edfd386b666637d67d4d10/pyasn1-modules-0.2.7.tar.gz : 0c35a52e00b672f832e5846826f1fb7507907f7d52fba6faa9e3c4cbe874fe4b
license    : BSD-2-Clause
component  : programming.python
summary    : A collection of ASN.1-based protocols modules
description: |
    A collection of ASN.1 modules expressed in form of pyasn1 classes. Includes protocols PDUs definition (SNMP, LDAP etc.) and various data structures (X.509, PKCS etc.).
builddeps  :
    - python-asn1
rundeps    :
    - python-asn1
    - python-openssl
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
#check      : |
#    %python_test
#    %python3_test
