name       : python-asn1-modules
version    : 0.0.8
release    : 1
source     :
    - https://pypi.python.org/packages/source/p/pyasn1-modules/pyasn1-modules-0.0.8.tar.gz : 10561934f1829bcc455c7ecdcdacdb4be5ffd3696f26f468eb6eb41e107f3837
license    : BSD-3-Clause
summary    : A collection of ASN.1-based protocols modules
description: |
    A collection of ASN.1-based protocols modules
builddeps  :
    - pkgconfig(python-2.7)
    - pkgconfig(python-3.5)
    - python-asn1
    - python-setuptools
    - python-openssl
rundeps    :
    - python-asn1
    - python-openssl
build      : |
    for py in "python" "python3" ; do
        ${py} setup.py build
    done
install    : |
    for py in "python" "python3" ; do
        ${py} setup.py install --root=%installroot% --no-compile -O0
    done
